// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJogfIeQS-sLku4YhCjJeYoGxWP_f5f7I',
    appId: '1:38507675908:web:375e7b0e0269c0899e9051',
    messagingSenderId: '38507675908',
    projectId: 'final-project-613dc',
    authDomain: 'final-project-613dc.firebaseapp.com',
    storageBucket: 'final-project-613dc.firebasestorage.app',
    measurementId: 'G-PMVMK46C4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGGLEZvyzMqAMml2_LJ7ZY3Nh-WiVGQE',
    appId: '1:38507675908:android:c1d00a976a20955f9e9051',
    messagingSenderId: '38507675908',
    projectId: 'final-project-613dc',
    storageBucket: 'final-project-613dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJg_2WhVGCHahy8bQYSyoreULjFFA024',
    appId: '1:38507675908:ios:9eba98e023209e549e9051',
    messagingSenderId: '38507675908',
    projectId: 'final-project-613dc',
    storageBucket: 'final-project-613dc.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbJg_2WhVGCHahy8bQYSyoreULjFFA024',
    appId: '1:38507675908:ios:9eba98e023209e549e9051',
    messagingSenderId: '38507675908',
    projectId: 'final-project-613dc',
    storageBucket: 'final-project-613dc.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJogfIeQS-sLku4YhCjJeYoGxWP_f5f7I',
    appId: '1:38507675908:web:971d8f5efe406d549e9051',
    messagingSenderId: '38507675908',
    projectId: 'final-project-613dc',
    authDomain: 'final-project-613dc.firebaseapp.com',
    storageBucket: 'final-project-613dc.firebasestorage.app',
    measurementId: 'G-0RQ77F6LEJ',
  );
}
